title: Zhan Cheng Homepage
page-top-title: Zhan Cheng Homepage
top-section-bg-text: "\"I personally think the riskier option is having an idea or project you're really passionate about and working at a safe, easy, unfulfilling job instead\", Sam Altman"
home-subtitle: Zhan Cheng
copyright-text: '&copy; Jerry Yin 2024. All Rights Reserved. Template by Jerry Yin From <a href="https://github.com/JerryYin777/JerryYin777.github.io">This Repo</a>.'
