title: Zhan Cheng Homepage
page-top-title: Zhan Cheng Homepage
top-section-bg-text: "\"I personally think the riskier option is having an idea or project you're really passionate about and working at a safe, easy, unfulfilling job instead\", Sam Altman"
home-subtitle: Zhan Cheng
copyright-text: '&copy; Zhan Cheng 2025. All Rights Reserved.'
